---
title: "Piano Lauree Scientifiche"
description: |
  **Laboratorio di Statistica**, Università degli Studi di Milano-Bicocca 
author:
  - name: Aldo Solari
    url: https://aldosolari.github.io/
    affiliation: DEMS
    affiliation_url: https://www.unimib.it/ateneo/dipartimenti-e-scuole/alla-scoperta-%E2%80%A6/dipartimento-economia-metodi-quantitativi-e-strategie-impresa
  - name: Laura Terzera
    affiliation: DISMEQ
    affiliation_url: https://www.dismeq.unimib.it/it
  - name: Stefano Barberis, Alice Giampino, Luca Danese, Pietro Meoni, Samuele Cassinari
    affiliation: Tutor
date: "`r Sys.Date()`"
output:
  radix::radix_article:
    toc: true
    toc_depth: 1
---



# La visione del mondo basata sui fatti

Il laboratorio di quest'anno prevede:

* l’utilizzo della statistica per
interpretare un fenomeno di interesse sulla base dei dati;

*  l’analisi di un questionario sulla conoscenza degli aspetti socio-economici del mondo di oggi;

* l'analisi dell'effetto ancoraggio. 

Secondo Carlo Rovelli

> Ragionamenti di tipo probabilistico e statistico sono uno strumento della ragione, potente e affilato. 
Non disporne ci lascia indifesi. 
Non avere chiarezza su nozioni come media, varianza, fluttuazioni e correlazioni è un pò come non sapere usare la moltiplicazione o la divisione. 

<aside>
Estratto da "Domenica" del "Sole 24 Ore", 20 Gennaio 2013. Tutti i diritti riservati.
</aside>

Tuttavia i numeri non bastano da soli. Il mondo non si può capire senza numeri né soltanto con i numeri: 

> In questo mondo incerto, chiedere certezze assolute è una sciocchezza.  Chi esibisce risposte certe è di solito il meno affidabile. 
Ma non per questo siamo nel buio. Fra certezza e totale incertezza vi è un prezioso spazio intermedio, ed è in questo spazio intermedio che si svolgono la nostra vita e il nostro pensiero.

Il laboratorio di quest’anno fa riferimento al libro *Factfulness*, sottotitolo:
*Dieci ragioni per cui non capiamo il mondo e perché le cose vanno
meglio*, dello statistico svedese Hans Rosling.  Secondo Bill Gates:


```{r, echo=FALSE}
library("htmltools")
library("vembedr")
embed_url("https://www.youtube.com/watch?v=5uooRe07mYM")
```

<aside>
Video pubblicato il 3 Aprile 2018 su **gatesnotes**: The blog of Bill Gates.
</aside>

Hans Rosling è stato un medico, statistico e accademico svedese. Membro dell’Accademia
di Svezia e del Karolinska Institutet, fondatore della sezione svedese
di Medici senza frontiere e infine della fondazione Gapminder, ha vissuto
vent’anni in Congo per studiare e combattere il konzo, una malattia
epidemica paralizzante.

# Le statistiche come terapia

Per comprendere in modo efficace lo sviluppo socio-economico mondiale bisogna saper leggere i dati.
Tutti parlano di come va il mondo, ma è raro vederlo fare con la forza dei numeri.

Rosling ci insegna ad avere una visione costruttiva del mondo, in cui il futuro torna serenamente, e con il supporto dei fatti, ad avere il segno +.

> Non va tutto male. Anzi, le cose non sono mai andate meglio; lo dicono i fatti. L'unico vero antidoto al luogo comune.

<aside>
Estratto dal libro **Factfulness**, Rizzoli.
</aside>

Nel libro *Factfulness*, Rosling presenta la *Carta della Salute Mondiale*.
Questo grafico è una sorta di mappa mondiale per la salute e la ricchezza. I punti cardinali Nord e Sud stanno per sani e malati. Est e Ovest stanno per ricchi e poveri.  

Ogni Paese è rappresentato da una bolla, grande in relazione alla sua dimensione (numero di persone); la salute è misurata in termini di aspettativa di vita alla nascita (in anni), mentre la ricchezza è misurata come reddito pro capite, in dollari per anno adeguati all'inflazione.

Provate a cercare il vostro Paese per vedere chi sono i Paesi vicini con reddito e salute simili, e osservare l'evoluzione nel tempo:

<head>

<link rel="stylesheet" href="//s3-eu-west-1.amazonaws.com/static.gapminderdev.org/vizabi/develop/vizabi.css">
<link rel="stylesheet" href="//s3-eu-west-1.amazonaws.com/static.gapminderdev.org/bubblechart.css">

<script src="//d3js.org/d3.v4.min.js"></script>
<script src="//s3-eu-west-1.amazonaws.com/static.gapminderdev.org/vizabi/develop/vizabi.min.js"></script>
<script src="//s3-eu-west-1.amazonaws.com/static.gapminderdev.org/preview/master/assets/vendor/js/vizabi-ws-reader/vizabi-ws-reader.js"></script>
<script src="//s3-eu-west-1.amazonaws.com/static.gapminderdev.org/systema-globalis/master/ConfigBubbleChart.js"></script>
<script src="//s3-eu-west-1.amazonaws.com/static.gapminderdev.org/bubblechart.js"></script>

</head>
<body>
<div id="placeholder" width="600px" height="400px"></div>

<script>
var wsReader = WsReader.WsReader.getReader();
Vizabi.Reader.extend("waffle", wsReader);

ConfigBubbleChart.locale = {
  "id": "en",
  "filePath": "//s3-eu-west-1.amazonaws.com/static.gapminderdev.org/vizabi/develop/assets/translation/"
};

ConfigBubbleChart.data = {
  "reader": "waffle",
  "path": "https://waffle-server-dev.gapminderdev.org/api/ddf/ql"
};

Vizabi("BubbleChart", document.getElementById("placeholder"), ConfigBubbleChart);
</script>

</body>

<aside>
SHOWING A FREE VIZUALIZATION FROM GAPMINDER.ORG, CC-BY LICENSE
</aside>

<br>

Dal 4 all'8 Febbraio 2019, studenti, familiari e amici delle scuole coinvolte hanno avuto la possibilità di rispondere ad un questionario di dieci domande sulla conoscenza degli aspetti socio-economici del mondo di oggi. 

Abbiamo raccolto 645 risposte al questionario. Com'è andata?

[**IL QUESTIONARIO**](docs/questionario.html)

Per i risultati dell'esperimento sull'effetto ancoraggio:

[**L'EFFETTO ANCORAGGIO**](docs/ancoraggio.html)

Per le slides:

[**SLIDES**](docs/slides.html)

Per il laboratorio:

[**LABORATORIO**](docs/laboratorio.html)


# Le scuole coinvolte

| Scuola | Comune | Studenti partecipanti |
|---|---|----|
| Liceo Scientifico E. Amaldi | Alzano Lombardo | 91 |
| Liceo Scientifico P. Frisi | Monza | 27 |
| Liceo Scientifico G. Marconi | Milano | 8 |
| Liceo Scientifico L. Mascheroni | Bergamo | 52  |
| Istituto di Istruzione Superiore L. Galvani | Milano | 49 |
| Liceo Classico e Linguistico A. Manzoni | Lecco | 1 |
| Liceo Scientifico A. Einstein | Milano | 27 |


# Il PLS di Statistica

L’Università degli Studi di Milano-Bicocca aderisce da anni all’iniziativa
del Piano delle Lauree Scientifiche (PLS) promossa dal Ministero dell’Università
e dell’Istruzione (MIUR). Il PLS è stato creato per diffondere la
conoscenza delle discipline scientifiche, inizialmente incluse nel progetto
in numero relativamente ridotto, solo nel 2010 è entrata ufficialmente la
disciplina Statistica dando luogo all’attività di Matematica-Statistica e
dal 2015 la Statistica ha acquisito completa autonomia. 

I due Corsi di laurea triennale di Statistica dell’Ateneo Milano-Bicocca,
convenendo sulla necessità di una maggiore conoscenza della Statistica
nelle Scuole secondarie di secondo grado, propongono attività
diversificate all’interno del PLS.

# I laboratori passati

Il Piano Lauree Scientifiche di Statistica propone come attività centrale
i *laboratori didattici*. Negli anni passati i laboratori hanno affrontato
il tema del gioco d’azzardo con l’obiettivo di presentare e discutere gli
aspetti di natura matematica, probabilistica e statistica legati ai diversi
giochi proposti.

*  Laboratorio “*Il gioco e il caso*”: condiviso con i corsi di Matematica,
prevede un laboratorio probabilistico sul tema del gioco d’azzardo
e un laboratorio statistico di analisi di questionari preventivamente
somministrati.

*  Laboratorio “*La statistica e il gioco*”: è programmato su un biennio
e prevede in un primo anno l’introduzione all’analisi statistica del
fenomeno attraverso somministrazione di questionari, nel secondo
anno simulazioni di gioco d’azzardo.

Le diverse attività di laboratorio sono rivolte a studenti delle scuole
secondarie di secondo grado dalla II classe. Obiettivo di questa azione
è rendere maggiormente consapevoli gli studenti delle scuole secondarie,
delle implicazioni probabilistiche del gioco d’azzardo e della diffusione di
tale fenomeno oltre a fornire strumenti di base statistici per interpretare
un fenomeno.


